version: '2'
services:
  app:
    container_name: willgarrett-app
    environment:
      - NEO4J_PASS:${NEO4J_PASS}
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: willgarrett/app
    volumes:
     -  .:/var/www/html
    ports:
     - "80:80"
    networks:
     - dub-net
  node:
    container_name: willgarrett-nodejs
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: willgarrett/node
    volumes:
     - ./node_src:/usr/app/
    ports:
      - "3000:3000"
    networks:
     - dub-net
  mysql:
    container_name: willgarrett-mysql
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - ./mysql_data:/var/lib/mysql
    networks:
     - dub-net
  redis:
    container_name: willgarrett-redis
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - dub-net
  neo4j:
    container_name: willgarrett-neo4j
    image: neo4j:3.0
    ports: 
    - "7474:7474"
    networks:
    - dub-net
    volumes:
    - ./neo4j_data/data:/data
    - ./neo4j_data/logs:/logs
networks:
  dub-net:
    driver: "bridge"
volumes:
  redisdata:
    driver: "local"